# baseURL = "http://www.arolla-cocoon.com/"
baseURL = "https://arolla-cocoon.netlify.com/"

languageCode = "en-us"
title = "Cocoon & Cosy luxury tents in Arolla"

theme = "airspace"

[menu]

  [[menu.header]]
    weight = 2
    name = "camping-arolla.com"
    url = "/work"

  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "camping-arolla.com"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"
  home = "Home"

  [params.slider]
    enable = true
    title = "Tentes de luxe COCOONING & COSY ...<br>Lit 2 personnes & Poële à bois"
    subtitle = "Vous avez toujours rêvé de venir camper, mais vous n’êtes pas un aventurier aguerri? <br> Venez passer une nuit inoubliable en plein coeur des montagnes, perchés à 1950m d'altitude, le tout dans une ambiance confortable & chaleureuse!"

  [params.wrapper]
    enable = true
    title = "A propos de nous / About Us ...Camping Arolla"
    italic = "Au coeur des Alpes suisses à 1 950 m d'altitude, vous apprécierez de pouvoir camper dans un environnement naturel au pied des sommets et glaciers. Il y a de très nombreuses randonnées et courses alpines au départ d'Arolla."
    paragraph = "In the heart of the Swiss Alps, at an altitude of 1 950 meters, Camping Arolla is situated in a beautiful position with a panorama of stunning mountains and glaciers. It offers dozens of routes and walks of every variety starting just a stone’s throw away."

  [params.feature]
    enable = true
    title = "Tentes de luxe / Luxury tents COCOONING & COSY"
    content = "TODO Bla bla sur les tentes"

  [params.call]
    enable = true
    title = "CALL XXXX"
    paragraph = "XXXXX"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
