baseURL = "http://www.cocoon-arolla.com/"
# baseURL = "https://arolla-cocoon.netlify.com/"

languageCode = "fr"
title = "Cocoon & Cosy tentes de luxe/luxury tents in Arolla"
theme = "airspace"

# Pas de Taxonomies
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "UA-121816579-1"

enableGitInfo = true
pygmentsCodeFences = true

[menu]

  [[menu.header]]
    weight = 2
    name = "www.camping-arolla.com"
    url = "http://www.camping-arolla.com"
  [[menu.header]]
    weight = 3
    name = "Prestations/services"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact & directions"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "www.camping-arolla.com"
    url = "http://www.camping-arolla.com"
  [[menu.footer]]
    weight = 2
    name = "Prestations/services"
    url = "/service"
  [[menu.footer]]
    weight = 3
    name = "Contact & directions"
    url = "/contact"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"
  home = "Home"

  description = "Tentes de luxe, lit 2 personnes & Poêle à bois. Vous avez toujours rêvé de venir camper, mais vous n’êtes pas un aventurier aguerri? Venez passer une nuit inoubliable en plein coeur des montagnes, perchés à 1950m d'altitude, le tout dans une ambiance confortable & chaleureuse!"

  [params.slider]
    enable = true
    title = "COCOONING & COSY"
    subtitle = "Tentes de luxe, lit 2 personnes & Poêle à bois.<br>Vous avez toujours rêvé de venir camper, mais vous n’êtes pas un aventurier aguerri? <br> Venez passer une nuit inoubliable en plein coeur des montagnes, perchés à 1950m d'altitude, le tout dans une ambiance confortable & chaleureuse!<p>Luxury Tents, 2 Person Bed & Wood Burning Stove. <br> Have you always dreamed of camping, but you are not a seasoned adventurer? <br> Come and spend an unforgettable night in the heart of the mountains, perched at 1950m altitude, all in a comfortable and warm atmosphere!"

  [params.wrapper]
    enable = true
    title = "A propos de nous / About Us ... Camping Arolla"
    italic = "Amoureux de la nature, venez découvrir le camping le plus haut d'Europe, perché à 1.950m d'altitude dans un environnement totalement naturel au pied des sommets et glaciers."
    paragraph = "In the heart of the Swiss Alps, at an altitude of 1 950 meters, Camping Arolla is situated in a beautiful position with a panorama of stunning mountains and glaciers. It offers dozens of routes and walks of every variety starting just a stone’s throw away."

  [params.feature]
    enable = true
    title = "Tentes de luxe / Luxury tents COCOONING & COSY"
    content = ""

  [params.call]
    enable = true
    title = "Apellez nous / Call us : +41 (0)27 283 22 95 "
    paragraph = "De Juin à Septembre / From June to September"

  [params.contact]
    enable = true
    title = "Contactez nous / Drop us a note"
    subtitle = "Utilisez le bouton de formulaire de contact à droite de la page / Use the contact form button on the right."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Camping Arolla"
      address = "Route de Tsalion - 1986 Arolla - Switzerland"
      email = "-"
      phone = "Téléphone / Phone: +41 (0)27 283 22 95"
    [params.contact.gmaps]
      title = "Nous trouver avec OpenStreet Maps / Find us with OpenStreet Maps"

# RGPD compliant
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
    enableDNT = true
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
